playbooks:
- name: experiment/greetings.yml
  extravars:
    custom_param: johndoe
- name: experiment/goodbye.yml
  extravars:
    custom_param: whiskey
    experiment: "true"
- name: experiment/goodbye.yml
  extraflags: "-vvv"
