plugin: community.docker.docker_containers
docker_host: unix://var/run/docker.sock
# add_legacy_groups: yes
keyed_groups:
  # Add containers with primary network foo to a network_foo group
  - prefix: network
    key: 'docker_hostconfig.NetworkMode'
  # Add Linux hosts to an os_linux group
  - prefix: os
    key: docker_platform
